### ISSUE TITLE
Customer settings for static url

### ISSUE THREAD

**Issue by clouds56** [jupyterlab/jupyterlab_launcher#14]
Now the static URL is constructed from base_url /lab and /static, and is not friendly for CDN.
Could it be moved into custom settings?

**Comment by blink1073** [comment]
Hi @clouds56, do I understand your request that you'd like `public_url` attribute in `LabConfig` that is `/static` by default?  What would the value be set to for the CDN case?  Is this intended to work with core JupyterLab, which adds other handlers like `/api/settings`?

**Comment by clouds56** [comment]
line 37 in [handlers.py](https://github.com/jupyterlab/jupyterlab_launcher/blob/master/jupyterlab_launcher/handlers.py):

        base_url = self.settings['base_url']
        url = ujoin(base_url, config.page_url, '/static/')

the `url` is now `"/lab/static"` and I'd like to change it to `"//some.cdn.org/jupyterlab/"`
so that when I load "https://localhost:8888/lab/static/main.bundle.js" it would use the cdn "https://some.cdn.org/jupyterlab/main.bundle.js" instead.

Is it possible?

so my idea is have a new `public_url` attribute in LabConfig that is `${base_url}${page_url}/static/` by default.

**Comment by blink1073** [comment]
Yep, that makes sense to me, thanks!
